//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC2BOA_win.Buisness
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildOrder
    {
        public int Id { get; set; }
        public string OnlineId { get; set; }
        public string race { get; set; }
        public string buildName { get; set; }
        public string buildInstrctions { get; set; }
    }
}
