//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC2BOA_win.Buisness
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.BuildOrders = new HashSet<BuildOrder>();
            this.MessagesSent = new HashSet<Message>();
            this.MessagesRecieved = new HashSet<Message>();
        }
    
        public long Id { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string OnlineId { get; set; }
        public int MessageId { get; set; }
    
        public virtual ICollection<BuildOrder> BuildOrders { get; set; }
        public virtual ICollection<Message> MessagesSent { get; set; }
        public virtual ICollection<Message> MessagesRecieved { get; set; }
    }
}
